update get peers method
hoprnet/hoprd-api-python pull request #8
Opened 2023-05-22 15:34 UTC by MartinBenediktBusch

2023-05-25 19:46 UTC, Teebor-Choka requested changes

2023-05-25 19:46 UTC, Teebor-Choka commented on src/hoprd/wrapper.py
> +        """
This is difficult to extend, I suggest using `**kwargs` as arguments to the function and then expansion into string, something like:

```python
args = "?" + "&".join([ f"{key}={value}" for k,v in kwargs.items() ]) if len(kwargs) > 0 else ""
```

And then pass these arguments as:

```python
        return await self.call_api(f"node/peers{args}", "GET", bytes(data, "utf-8"))
```

Also, this would be a nice API change for the future, this should be passed as data, not as a URL.
The args part can also be extracted as a separate function usable with call_api anywhere.

2023-05-25 19:47 UTC, Teebor-Choka commented
Please, use PR descriptions and tags on the PRs.

2023-05-25 20:55 UTC, MartinBenediktBusch commented on src/hoprd/wrapper.py
> +        """
Nice thanks for the advice :) Will include descriptions and labels form now on. I incorporated your suggestion in a new commit now. However, I have not tested the changes yet as I have currently no access to my node. Will request a further review once I tested the changes with my avado.

2023-05-29 08:53 UTC, MartinBenediktBusch commented
changes tested with Avado version 1.93.7 in monte rosa.

2023-05-29 08:57 UTC, Teebor-Choka approved these changes

2023-05-29 08:58 UTC, merged